name: Build and Deploy
on:
  push:
    branches:
      - main
  schedule:
    - cron: "37 4 * * *" # nightly
  workflow_dispatch:

permissions:
  contents: write
jobs:
  generate-ics:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: 3.x
      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          key: pip-cache-${{ hashFiles('requirements.txt') }}
          path: ~/.cache/pip
          restore-keys: |
            pip-cache-
      - run: pip install -r requirements.txt
      - name: Generate ICS files
        env:
          TFL_API_KEY: ${{ secrets.TFL_API_KEY }}
        run: python generate_ics.py

  deploy:
    runs-on: ubuntu-latest
    needs: generate-ics
    if: always()
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: 3.x
      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          key: pip-cache-${{ hashFiles('requirements.txt') }}
          path: ~/.cache/pip
          restore-keys: |
            pip-cache-
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
