name: Deploy Docs

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Generate ics files"]
    types:
      - completed

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: 3.x
      - uses: actions/cache@v4.2.3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install -r requirements.txt

      - uses: actions/cache/restore@v4.2.3
        with:
          path: docs/calendars
          key: ics-files
          fail-on-cache-miss: true
      - run: mkdocs gh-deploy --force
